### ISSUE TITLE
기본 로그인 기능

### ISSUE THREAD

**Issue by HannaJeon** [code-squad/woowahan-2018#2]
- 프론트엔드
    - 각 항목을 선택하면 placeholder내용이 사라집니다. (애니메이션 없음)
    - 로그인에 실패하면, 잘못된 정보를 받아서 email 필드에 로그인정보가 틀렸습니다 라고 노출된다.

- 백엔드
    - 유저의 정보와 다른경우 Ajax를 통해서 응답을 처리해야 한다.
    - 유저의 정보가 같은경우 로그인 성공하고 세션유지한다.

**Comment by skim451** [comment]
리뷰하였습니다.
