### ISSUE TITLE
회원가입 기능

### ISSUE THREAD

**Issue by HannaJeon** [code-squad/woowahan-2018#3]
- 프론트엔드
    - 각 항목을 선택하면 placeholder내용이 사라집니다. (애니메이션 없음)
    - 비어있는 상태로 ‘가입하기'를 선택하면 비어있는 항목에 빨간색으로 ‘값을 입력해주세요' 라고 노출되고 focus가 간다.
    - 패스워드는 10자이상이어야 하며, 문자,숫자,2개 이상의 특수문자가 포함되야 한다. 패스워드 규칙은 자바스크립트로 구현한다.
    - Ajax를 통해서 요청/응답을 처리해야 한다.
    - 이미 존재하는 사용자인 경우, 이미 가입된 사용자라는 정보가 존재한다는 메시지가 해당 username이나 email에 노출된다.

- 백엔드
    - 패스워드는 10자이상이어야 하며, 문자,숫자,2개 이상의 특수문자가 포함되야 한다.
    - 이미 존재하는 사용자인 경우, 이미 가입된 사용자라는 정보가 존재한다는 메시지를 Ajax를 통해서 응답을 처리해야 한다.

**Comment by javajigi** [comment]
* 회원가입, 로그인과 같은 기능은 ajax로 구현한다.

## 서버측 유효성 체크와 관련해 참고할 자료
* https://www.mkyong.com/spring-mvc/spring-rest-api-validation/
* https://www.leveluplunch.com/java/tutorials/017-validate-spring-rest-webservice-request/
* http://www.bbenson.co/post/spring-validations-with-examples/

유효성 체크는 java validation과 spring의 @Valid 애노테이션 활용해 진행해 보세요.
