### ISSUE TITLE
ec2 셋팅

### ISSUE THREAD

**Issue by HannaJeon** [code-squad/woowahan-2018#5]
- was서버용 ec2 생성한다.
- db용 ec2를 생성한다.(private)
- db용 ec2에 mysql을 설치한다.
- 자동배포 쉘 스크립트를 만든다.

**Comment by javajigi** [comment]
@HannaJeon 
https://nextstep.camp/courses/-L0xMaGD-nVimTzZT8Us/-L4ZUG2VBqrcJxtJhL2Y/lessons/-L5BhtVobOE6kP9OpKQZ 문서 참고해 spring profile 적용해 보세요.

개발 서버에서 db를 분리할 경우 ec2 인스턴스를 매일 stop해야되기 때문에 ip가 변경되어 설정을 바꿔야하는 불편함이 있을 겁니다. 개발 서버는 db를 같은 곳에서 운영하고 실 서비스를 하는 경우에는 분리하는 것이 좋지 않을까라고 조심스럽게 제안해 봅니다.
