### ISSUE TITLE
[Demo용] 퀄리티를 올려보자!

### ISSUE THREAD

**Issue by skim451** [code-squad/woowahan-2018#62]
- [x] Board.html에서 보드 이름 길이에 제한을 두자. (프론트 & 백엔드 DB) 20자 제한
- [x] board.html에서 보드 추가를 하다 말고 modal을 끄면 boardname이 초기화되도록 하자. 
- [x] boards.html에서 members를 보면 매번 javajigi가 방장인 것처럼 나오는데 지금 사용자가 나올 수 있도록 하자.
- [x] boards.html에서 deck이름 필드에 길이 제한을 두자. (20자) 
- [x] boards.html에서 빈 string으로 deck 생성 시도시 에러 메세지가 undefined로 나온다.
- [x] boards.html에서 에러메세지를 .warning modal에 보여줄 수 있게 하자.
- [x] boards.html에서 웬일인지 deck이름이 수정 가능하게 프론트가 되어있는데 막아놓자.

**Comment by woowa-kkiluk** [comment]
- [x] 덱, 카드 추가 시 input에 자동 포커스

**Comment by woowa-kkiluk** [comment]
- [ ] 모달이 떠있는 상황에 모달 바깥 공간(?) 선택 시, 모달 close

**Comment by skim451** [comment]
[ ] card modal에서 attachment버튼을 없애버리자. (미구현)

**Comment by skim451** [comment]
[ ] card modal에서 activity라고 써있는 부분을 없애버리자. (미구현)

**Comment by saram4030** [comment]
- [ ] 멤버스 모달에서 submit 버튼 못생김

**Comment by woowa-kkiluk** [comment]
- [ ] 이거 닫아주세요. 한번에 하나만 뜨도록
![image](https://user-images.githubusercontent.com/2840675/36883638-1e1721c8-1e1f-11e8-914b-973ac18f1576.png)

**Comment by skim451** [comment]
- [ ] 회원가입에서 가입하기 버튼 밑에 여백이 너무 좁음

**Comment by woowa-kkiluk** [comment]
- [x] 멤버스 버튼 왜 요기 있징?
![image](https://user-images.githubusercontent.com/2840675/36883669-56e4e7ec-1e1f-11e8-9c1d-be71f6f89573.png)

**Comment by Jeju-Boobby** [comment]
modal에서 member, due date 같이 열리는거 해결

**Comment by skim451** [comment]
- [ ] 상단 app bar에 JWP Trello에 홈으로 가는 링크 좀 달아주세요.

**Comment by saram4030** [comment]
- [ ] 지금 4시 아닌데...
![image](https://user-images.githubusercontent.com/2840675/36883724-af752638-1e1f-11e8-8be7-41c9161bdb5f.png)

**Comment by woowa-kkiluk** [comment]
- [x] 덱 만들 때, 이름 쓰다가 엔터 누르면 save 되게 해주세요.

**Comment by saram4030** [comment]
- [ ] 보드 페이지에서 이거 누르면 index? board(refresh)? 페이지로 이동하도록 해주세요.

**Comment by skim451** [comment]
- [x] 그 뭐냐 회원가입화면에서 "가입하기"를 클릭해야 버튼 먹는거 해결 좀. (글자 옆에 여백을 누르면 버튼이 안 눌림...)

**Comment by saram4030** [comment]
- [ ] 멤버스 순서 픽스해주세요. 
![image](https://user-images.githubusercontent.com/2840675/36883867-68e91fde-1e20-11e8-8bde-92a6608baeb0.png)
![image](https://user-images.githubusercontent.com/2840675/36883874-74f643b0-1e20-11e8-9391-9f2c5b0fe25f.png)

**Comment by saram4030** [comment]
- [ ] 디스크립션만 색깔이 암울해요.
![image](https://user-images.githubusercontent.com/2840675/36883886-97219098-1e20-11e8-837e-ffec3f8921da.png)

**Comment by saram4030** [comment]
- [ ] 모달이 커졌을 때 아랫 부분이 잘려요...... 스크롤 아무리 내려도ㅠㅠ
![image](https://user-images.githubusercontent.com/2840675/36883995-56cdff80-1e21-11e8-8fd5-d67b16a2f1be.png)
